/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Premium Color Palette
        "primary": {
          DEFAULT: "#1a1a2e",
          light: "#16213e",
          dark: "#0f0f1e",
        },
        "accent": {
          DEFAULT: "#d4af37",
          light: "#e8c468",
          dark: "#c49d2d",
        },
        "surface-bright": "#fafafa",
        "surface-container-highest": "#f5f5f5",
        "on-secondary-container": "#4e6874",
        "outline-variant": "#e0e0e0",
        "surface-container-high": "#f8f8f8",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#16213e",
        "background": "var(--background, #fafafa)",
        "surface": "var(--surface, #ffffff)",
        "on-secondary-fixed": "#1a1a1a",
        "secondary-fixed-dim": "#afcbd8",
        "on-secondary": "var(--on-primary, #ffffff)",
        "on-secondary-fixed-variant": "#616161",
        "on-primary": "var(--on-primary, #ffffff)",
        "tertiary-container": "#f5f5f5",
        "secondary-fixed": "#fafafa",
        "on-background": "var(--on-background, #1a1a1a)",
        "surface-dim": "#f5f5f5",
        "tertiary-fixed-dim": "#e0e0e0",
        "error-container": "#ffdad6",
        "secondary": "#616161",
        "primary-container": "#16213e",
        "outline": "var(--outline, #9e9e9e)",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#fafafa",
        "on-primary-fixed": "#1a1a2e",
        "inverse-primary": "#d4af37",
        "surface-container-low": "#fafafa",
        "on-tertiary-fixed": "#1a1a1a",
        "on-tertiary-fixed-variant": "#616161",
        "surface-tint": "#d4af37",
        "on-tertiary-container": "#1a1a1a",
        "inverse-on-surface": "#ffffff",
        "surface-variant": "var(--surface-variant, #f5f5f5)",
        "error": "#ba1a1a",
        "secondary-container": "#f5f5f5",
        "surface-container": "#ffffff",
        "on-surface-variant": "var(--on-surface-variant, #616161)",
        "inverse-surface": "#1a1a2e",
        "on-surface": "var(--on-surface, #1a1a1a)",
        "on-primary-container": "#ffffff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#16213e",
        "tertiary": "#9e9e9e",
        "primary-fixed": "#1a1a2e",
        "on-error": "#ffffff"
      },
      fontFamily: {
        "headline": ["Playfair Display", "serif"],
        "body": ["Poppins", "sans-serif"],
        "label": ["Poppins", "sans-serif"]
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.6s ease-out',
        'fade-in': 'fadeIn 0.4s ease-out',
        'scale-in': 'scaleIn 0.5s cubic-bezier(0.34, 1.56, 0.64, 1)',
        'slide-in-right': 'slideInRight 0.6s ease-out',
        'slide-in-left': 'slideInLeft 0.6s ease-out',
        'float': 'float 3s ease-in-out infinite',
        'shimmer': 'shimmer 2s infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
      },
      boxShadow: {
        'premium': '0 10px 40px rgba(0, 0, 0, 0.1), 0 2px 8px rgba(0, 0, 0, 0.06)',
        'premium-lg': '0 20px 60px rgba(0, 0, 0, 0.15), 0 4px 12px rgba(0, 0, 0, 0.08)',
        'glow': '0 0 20px rgba(212, 175, 55, 0.3)',
        'glow-lg': '0 0 40px rgba(212, 175, 55, 0.5)',
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
}