/* eslint-disable react-refresh/only-export-components */
import React, { createContext, useState, useContext, useMemo } from 'react';

import {
  translateCategoryName,
  translateProductName,
  translateProductDescription,
  translateOrderStatus,
  translateColorName,
} from '../utils/i18nHelpers';

const LanguageContext = createContext();

const translations = {
  vi: {
    nav: {
      home: 'Trang chủ',
      products: 'Sản phẩm',
      brand: 'Thương hiệu',
      offers: 'Ưu đãi',
      contact: 'Liên hệ',
      searchPlaceholder: 'Tìm kiếm sản phẩm...',
      searchNoResults: 'Không tìm thấy "{query}"',
      searchViewAll: 'Xem tất cả sản phẩm',
      admin: 'Quản trị viên',
      staff: 'Nhân viên',
      customer: 'Khách hàng',
      welcome: 'Chào, {name}',
      logout: 'Đăng xuất',
      myAccount: 'Tài khoản của tôi',
      adminPanel: 'Vào trang Quản trị',
      backToWebsite: 'Quay về Website',
      loginOrRegister: 'Đăng nhập / Đăng ký',
      searchProduct: 'Tìm sản phẩm',
      close: 'Đóng'
    },
    notifications: {
      title: 'Thông báo',
      empty: 'Không có thông báo mới',
      markAllRead: 'Đánh dấu tất cả đã đọc',
      viewAll: 'Xem tất cả',
      justNow: 'Vừa xong'
    },
    home: {
      heroSub: 'Bộ sưu tập Thu Đông 2026',
      heroTitle: 'Định nghĩa lại sự tinh tế.',
      heroDesc: 'Khám phá những sản phẩm được giám tuyển kỹ lưỡng, kết hợp giữa nghệ thuật thủ công truyền thống và tư duy thiết kế đương đại.',
      heroBtn: 'Mua sắm ngay',
      categoriesTitle: 'Danh mục nổi bật',
      categoriesSub: 'Khám phá thế giới phong cách riêng biệt',
      viewAllCategories: 'Xem tất cả danh mục',
      explore: 'Khám phá ngay',
      newArrivalsTitle: 'Sản phẩm mới nhất',
      newArrivalsSub: 'Những tác phẩm vừa mới cập bến Aura K, sẵn sàng để trở thành một phần trong phong cách của bạn.',
      newsletterTitle: 'Gia nhập cộng đồng Aura K',
      newsletterDesc: 'Đăng ký để nhận những cập nhật mới nhất về các bộ sưu tập giới hạn và xu hướng phong cách đương đại.',
      newsletterPlaceholder: 'Địa chỉ email của bạn',
      newsletterBtn: 'Đăng ký',
      newsletterSuccess: 'Tuyệt vời! Đang chuyển hướng đến trang đăng ký...',
      newsletterRegistered: 'Email này đã có tài khoản. Vui lòng đăng nhập!',
      feature1Title: 'Chất lượng Giám tuyển',
      feature1Desc: 'Mỗi sản phẩm đều trải qua quy trình kiểm định khắt khe về nguồn gốc và chất liệu trước khi đến tay bạn.',
      feature2Title: 'Giao hàng Ưu tiên',
      feature2Desc: 'Trải nghiệm dịch vụ giao hàng cao cấp, an toàn và nhanh chóng trong vòng 24-48 giờ trên toàn quốc.',
      feature3Title: 'Đặc quyền Thành viên',
      feature3Desc: 'Tham gia chương trình Aura K Elite để nhận những ưu đãi độc quyền và lời mời tham dự các sự kiện riêng tư.',
      fallbackSubtitle: {
        pants: 'Năng động và thoải mái',
        jackets: 'Giữ ấm đầy phong cách',
        tshirts: 'Thoải mái mỗi ngày',
        dresses: 'Nét duyên dáng, nữ tính',
        women: 'Sự sang trọng vượt thời gian',
        men: 'Phong cách lịch lãm',
        home: 'Nâng tầm không gian sống',
        accessories: 'Điểm nhấn hoàn hảo'
      },
      premiumLabel: 'Cao cấp',
      premiumBrandsTitle: 'Thương hiệu cao cấp',
      premiumBrandsSub: 'Những nhãn hàng boutique với chất liệu tinh chọn và thiết kế tinh tế.',
      premiumBadge: 'Couture',
      noBrandTier: 'Chưa phân loại (thiếu thông tin từ backend)',
      noBrandData: 'Chưa có dữ liệu thương hiệu',
      mainstreamLabel: 'Bình dân',
      mainstreamBrandsTitle: 'Thương hiệu phổ thông',
      mainstreamBrandsSub: 'Đối tượng dễ tiếp cận với phong cách linh hoạt, phù hợp cuộc sống hiện đại.',
      mainstreamBadge: 'Street',
      brandExplore: 'Khám phá'
    },
    footer: {
      desc: 'Được thành lập với tầm nhìn mang lại những giá trị thẩm mỹ bền vững, Aura K là điểm đến cho những tâm hồn tìm kiếm sự tinh tế và khác biệt trong từng chi tiết nhỏ.',
      explore: 'Khám phá',
      support: 'Hỗ trợ',
      collections: 'Bộ sưu tập',
      newArrivals: 'Sản phẩm mới',
      men: 'Nam giới',
      women: 'Nữ giới',
      contact: 'Liên hệ',
      stores: 'Hệ thống cửa hàng',
      privacy: 'Chính sách bảo mật',
      terms: 'Điều khoản sử dụng',
      partners: 'Đối tác & Tài trợ',
      rights: '© 2026 Aura K. Bảo lưu mọi quyền.'
    },
    checkout: {
      title: 'Thanh toán',
      shippingAddress: 'Thông tin giao hàng',
      shippingInfo: 'Thông tin vận chuyển',
      complete: 'Hoàn tất',
      contactInfo: 'Thông tin liên hệ',
      alreadyHaveAccount: 'Đã có tài khoản?',
      street: 'Địa chỉ cụ thể',
      lastName: 'Họ',
      firstName: 'Tên',
      fullName: 'Họ và tên',
      fullNamePlaceholder: 'Nhập họ và tên...',
      phone: 'Số điện thoại',
      phonePlaceholder: 'Nhập số điện thoại...',
      city: 'Tỉnh / Thành phố',
      cityPlaceholder: 'Chọn Tỉnh / Thành phố',
      district: 'Quận / Huyện',
      districtPlaceholder: 'Chọn Quận / Huyện',
      ward: 'Phường / Xã',
      wardPlaceholder: 'Chọn Phường / Xã',
      addressDetail: 'Địa chỉ cụ thể',
      addressDetailPlaceholder: 'Số nhà, tên đường...',
      paymentMethod: 'Phương thức thanh toán',
      cod: 'Thanh toán khi nhận hàng (COD)',
      codDesc: 'Thanh toán bằng tiền mặt khi nhận hàng.',
      onlinePayment: 'Thanh toán Ví điện tử MoMo',
      onlinePaymentDesc: 'Sử dụng ứng dụng MoMo để quét mã QR thanh toán nhanh.',
      bankTransfer: 'Chuyển khoản Ngân hàng (Vietcombank)',
      bankTransferDesc: 'Chuyển khoản trực tiếp qua số tài khoản ngân hàng của shop.',
      orderSummary: 'Chi tiết đơn hàng',
      placeOrder: 'Đặt hàng ngay',
      orderSuccessTitle: 'Đặt hàng thành công!',
      orderSuccessMessage: 'Cảm ơn bạn đã mua sắm tại Aura K. Đơn hàng của bạn đã được tiếp nhận và đang xử lý.',
      orderId: 'Mã đơn hàng',
      backToHome: 'Quay về trang chủ',
      requiredFields: 'Vui lòng điền đầy đủ các thông tin bắt buộc!',
      loading: 'Đang xử lý...',
      cartEmpty: 'Giỏ hàng của bạn đang trống. Vui lòng thêm sản phẩm trước khi thanh toán.'
    },
    account: {
      sidebarAccount: 'Tài khoản của tôi',
      sidebarOrders: 'Đơn hàng của tôi',
      sidebarAddresses: 'Sổ địa chỉ',
      sidebarVouchers: 'Kho Voucher',
      sidebarLogout: 'Đăng xuất',
      profile: 'Hồ sơ của tôi',
      profileSub: 'Quản lý thông tin hồ sơ để bảo mật tài khoản',
      personalInfo: 'Thông tin cá nhân',
      edit: 'Chỉnh sửa',
      save: 'Lưu thay đổi',
      firstName: 'Tên',
      lastName: 'Họ',
      username: 'Tên đăng nhập',
      phone: 'Số điện thoại',
      email: 'Địa chỉ Email',
      gender: 'Giới tính',
      male: 'Nam',
      female: 'Nữ',
      other: 'Khác',
      addressBook: 'Sổ địa chỉ',
      addNewAddress: 'Thêm địa chỉ mới',
      noAddresses: 'Bạn chưa lưu địa chỉ nào.',
      orderHistory: 'Lịch sử mua hàng',
      orderId: 'Mã đơn hàng',
      date: 'Ngày đặt',
      total: 'Tổng tiền',
      status: 'Trạng thái',
      viewDetail: 'Xem chi tiết',
      noOrders: 'Bạn chưa có đơn hàng nào.',
      voucherCode: 'Mã',
      discount: 'Giảm',
      minSpend: 'Đơn tối thiểu',
      expiry: 'Hạn sử dụng',
      useNow: 'Dùng ngay',
      noVouchers: 'Không có voucher nào khả dụng.',
      orderDetail: 'Chi tiết đơn hàng',
      backToHistory: 'Quay lại lịch sử đơn hàng',
      receiverInfo: 'Thông tin người nhận',
      paymentStatus: 'Thành toán',
      paid: 'Đã thanh toán',
      unpaid: 'Chưa thanh toán',
      orderStatus: {
        pending: 'Chờ xác nhận',
        confirmed: 'Đã xác nhận',
        shipping: 'Đang giao hàng',
        delivered: 'Đã giao hàng',
        cancelled: 'Đã hủy'
      }
    },
    loginRegister: {
      loginTitle: 'Chào mừng trở lại',
      loginDesc: 'Đăng nhập vào tài khoản của bạn để tiếp tục mua sắm tại Aura K.',
      registerTitle: 'Tạo tài khoản mới',
      registerDesc: 'Đăng ký tài khoản để nhận nhiều ưu đãi đặc quyền và quản lý đơn hàng tốt hơn.',
      email: 'Địa chỉ Email',
      password: 'Mật khẩu',
      confirmPassword: 'Xác nhận mật khẩu',
      forgotPassword: 'Quên mật khẩu?',
      loginBtn: 'Đăng nhập',
      registerBtn: 'Đăng ký',
      noAccount: 'Chưa có tài khoản?',
      hasAccount: 'Đã có tài khoản?',
      googleLogin: 'Đăng nhập với Google',
      facebookLogin: 'Đăng nhập với Facebook',
      username: 'Tên tài khoản',
      required: 'Trường này là bắt buộc'
    },
    common: {
      yes: 'Có',
      no: 'Không',
      cancel: 'Huỷ',
      confirm: 'Xác nhận',
      save: 'Lưu',
      edit: 'Chỉnh sửa',
      delete: 'Xoá',
      loading: 'Đang tải...',
      seeMore: 'Xem thêm',
      seeLess: 'Thu gọn',
      search: 'Tìm kiếm',
      all: 'Tất cả',
      back: 'Quay lại',
      next: 'Tiếp theo',
      previous: 'Trước',
      or: 'hoặc',
      and: 'và',
      from: 'Từ',
      to: 'đến',
      free: 'Miễn phí',
      sold: 'đã bán',
      welcome: 'Xin chào',
      error: 'Lỗi',
      success: 'Thành công',
      processing: 'Đang xử lý...',
      empty: 'Không có dữ liệu',
      retry: 'Thử lại',
    },
    header: {
      searchPlaceholder: 'Tìm sản phẩm, thương hiệu...',
      darkMode: 'Chế độ tối',
      lightMode: 'Chế độ sáng',
      languageLabel: 'Ngôn ngữ',
      notifications: 'Thông báo',
      markAllRead: 'Đánh dấu tất cả đã đọc',
      noNotifications: 'Không có thông báo mới',
      viewAllNotifs: 'Xem tất cả',
      cart: 'Giỏ hàng',
      emptyCart: 'Giỏ hàng đang trống',
      wishlist: 'Yêu thích',
      accountMenu: 'Tài khoản',
      login: 'Đăng nhập',
      register: 'Đăng ký',
      customerService: 'Hỗ trợ khách hàng',
      hotlineLabel: 'Hotline',
    },
    products: {
      title: 'Tất cả sản phẩm',
      filterCategory: 'Danh mục',
      filterBrand: 'Thương hiệu',
      filterPrice: 'Khoảng giá',
      sortBy: 'Sắp xếp theo',
      sortNewest: 'Mới nhất',
      sortPriceAsc: 'Giá: Thấp đến Cao',
      sortPriceDesc: 'Giá: Cao đến Thấp',
      sortBestSell: 'Bán chạy nhất',
      sortAZ: 'Tên: A-Z',
      sortZA: 'Tên: Z-A',
      searchLabel: 'Tìm kiếm',
      noProducts: 'Không tìm thấy sản phẩm nào phù hợp.',
      tryDifferent: 'Hãy thử điều chỉnh bộ lọc hoặc từ khoá tìm kiếm.',
      allCategories: 'Tất cả danh mục',
      allBrands: 'Tất cả thương hiệu',
      priceFrom: 'Từ',
      priceTo: 'Đến',
      applyFilter: 'Áp dụng',
      clearFilter: 'Xoá bộ lọc',
      showingResults: 'Hiển thị {count} sản phẩm',
      category: 'Danh mục',
      brand: 'Thương hiệu',
      addToCart: 'Thêm vào giỏ',
      newBadge: 'Mới',
      outOfStock: 'Hết hàng',
      inStock: 'Còn hàng',
      filterTitle: 'Bộ lọc',
      view: 'Xem',
      viewAll: 'Xem tất cả',
      results: 'kết quả',
      auraKBrand: 'Aura K',
    },
    productDetail: {
      addToCart: 'Thêm vào giỏ hàng',
      buyNow: 'Mua ngay',
      outOfStock: 'Hết hàng',
      description: 'Mô tả chi tiết',
      specs: 'Thông số kỹ thuật',
      reviews: 'Đánh giá',
      relatedProducts: 'Sản phẩm liên quan',
      relatedDesc: 'Có thể bạn cũng sẽ thích những sản phẩm được gợi ý này.',
      size: 'Kích cỡ',
      color: 'Màu sắc',
      quantity: 'Số lượng',
      share: 'Chia sẻ',
      addSuccess: 'Đã thêm sản phẩm vào giỏ hàng!',
      brand: 'Thương hiệu',
      category: 'Danh mục',
      status: 'Tình trạng',
      inStock: 'Còn hàng',
      sold: 'Đã bán',
      rating: 'Đánh giá',
      writeReview: 'Viết đánh giá',
      reviewPlaceholder: 'Chia sẻ cảm nhận của bạn...',
      submitReview: 'Gửi đánh giá',
      reviewSubmitted: 'Cảm ơn bạn đã đánh giá!',
      noReviews: 'Chưa có đánh giá nào cho sản phẩm này.',
      viewCart: 'Xem giỏ hàng',
      backToShop: 'Tiếp tục mua sắm',
      sku: 'Mã SKU',
      tags: 'Thẻ',
      flashSale: 'Flash Sale',
      customerReviews: 'Đánh giá khách hàng',
      reviewsTitle: 'Cảm nhận từ cộng đồng',
      yourRating: 'Đánh giá của bạn',
      yourComment: 'Nội dung đánh giá',
      loginToReview: 'Vui lòng đăng nhập để gửi đánh giá.',
      loginToReviewMessage: 'Vui lòng đăng nhập để chia sẻ trải nghiệm của bạn về sản phẩm này.',
      emptyReview: 'Vui lòng nhập nội dung đánh giá.',
      reviewFailed: 'Không thể gửi đánh giá lúc này.',
      serverError: 'Lỗi kết nối đến server.',
      loading: 'Đang tải sản phẩm...',
      loadingReviews: 'Đang tải đánh giá...',
      notFound: 'Không tìm thấy sản phẩm.',
      connectionError: 'Không thể kết nối đến server.',
      selectSize: 'Vui lòng chọn kích thước!',
      selectColor: 'Vui lòng chọn màu sắc!',
      sizeGuide: 'Hướng dẫn chọn size',
      sizeGuideUnit: 'Đơn vị: cm',
      howToMeasure: 'Cách đo đạc',
      chest: 'Vòng ngực',
      chestDesc: 'Đo phần to nhất của ngực, giữ thước nằm ngang.',
      waist: 'Vòng eo',
      waistDesc: 'Đo phần nhỏ nhất của eo bụng, thường trên rốn 2–3cm.',
      hips: 'Vòng mông',
      hipsDesc: 'Đo phần rộng nhất của phần mông.',
      height: 'Chiều cao',
      sizeTip: 'Để mặc thoải mái, nếu số đo nằm giữa 2 size, hãy chọn size lớn hơn.',
      gotIt: 'Đã hiểu!',
      auraCustomer: 'Khách hàng Aura K',
      noComment: 'Khách hàng không để lại bình luận.',
      beFirstReviewer: 'Hãy trải nghiệm và trở thành người đầu tiên đánh giá sản phẩm này nhé.',
      youMayAlsoLike: 'Có thể bạn cũng thích',
    },
    cart: {
      title: 'Giỏ hàng của bạn',
      empty: 'Giỏ hàng trống',
      emptySub: 'Chưa có sản phẩm nào trong giỏ hàng của bạn.',
      backToShop: 'Quay lại mua sắm',
      product: 'Sản phẩm',
      price: 'Giá',
      quantity: 'Số lượng',
      total: 'Tổng cộng',
      summary: 'Tóm tắt đơn hàng',
      subtotal: 'Tạm tính',
      shipping: 'Phí giao hàng',
      shippingFree: 'Miễn phí',
      checkout: 'Tiến hành thanh toán',
      remove: 'Xoá',
      clear: 'Xoá tất cả',
      discount: 'Giảm giá',
      voucher: 'Mã giảm giá',
      applyVoucher: 'Áp dụng',
      voucherPlaceholder: 'Nhập mã giảm giá...',
      voucherApplied: 'Đã áp dụng mã giảm giá {code}!',
      voucherInvalid: 'Mã giảm giá không hợp lệ hoặc đã hết hạn.',
      voucherExpired: 'Mã giảm giá đã hết hạn.',
      continueShopping: 'Tiếp tục mua sắm',
      cartUpdated: 'Đã cập nhật giỏ hàng.',
      removedItem: 'Đã xoá sản phẩm khỏi giỏ hàng.',
      orderSummary: 'Chi tiết thanh toán',
    },
    contact: {
      title: 'Liên hệ với chúng tôi',
      subtitle: 'Chúng tôi luôn sẵn lòng lắng nghe bạn',
      name: 'Họ và tên',
      namePlaceholder: 'Nhập họ và tên...',
      email: 'Địa chỉ Email',
      emailPlaceholder: 'you@example.com',
      phone: 'Số điện thoại',
      phonePlaceholder: 'Nhập số điện thoại...',
      subject: 'Tiêu đề',
      subjectPlaceholder: 'Chủ đề bạn muốn trao đổi...',
      message: 'Nội dung',
      messagePlaceholder: 'Nhập nội dung liên hệ...',
      send: 'Gửi liên hệ',
      sending: 'Đang gửi...',
      sendSuccess: 'Gửi liên hệ thành công! Chúng tôi sẽ phản hồi sớm.',
      sendError: 'Gửi liên hệ thất bại. Vui lòng thử lại sau.',
      ourInfo: 'Thông tin liên hệ',
      ourAddress: 'Địa chỉ',
      ourPhone: 'Điện thoại',
      ourEmail: 'Email',
      ourHours: 'Giờ mở cửa',
      faqTitle: 'Câu hỏi thường gặp',
      followUs: 'Theo dõi chúng tôi',
    },
    address: {
      title: 'Sổ địa chỉ',
      addNew: 'Thêm địa chỉ mới',
      noAddresses: 'Bạn chưa lưu địa chỉ nào. Hãy thêm địa chỉ để thanh toán nhanh hơn.',
      recipientName: 'Họ và tên',
      recipientPhone: 'Số điện thoại',
      addressDetail: 'Địa chỉ cụ thể',
      city: 'Tỉnh/Thành phố',
      district: 'Quận/Huyện',
      ward: 'Phường/Xã',
      isDefault: 'Đặt làm địa chỉ mặc định',
      setDefault: 'Đặt mặc định',
      edit: 'Chỉnh sửa',
      delete: 'Xoá',
      confirmDelete: 'Bạn có chắc muốn xoá địa chỉ này?',
      addSuccess: 'Đã thêm địa chỉ thành công.',
      updateSuccess: 'Đã cập nhật địa chỉ.',
      deleteSuccess: 'Đã xoá địa chỉ.',
      selectAddress: 'Chọn địa chỉ',
      defaultLabel: 'Mặc định',
      empty: 'Chưa có',
      loading: 'Đang tải địa chỉ...',
      required: 'Vui lòng nhập đầy đủ thông tin.',
    },
    order: {
      title: 'Đơn hàng của tôi',
      orderId: 'Mã đơn hàng',
      orderDate: 'Ngày đặt',
      totalAmount: 'Tổng tiên',
      status: 'Trạng thái',
      viewDetail: 'Xem chi tiết',
      noOrders: 'Bạn chưa có đơn hàng nào.',
      backToShop: 'Mua sắm ngay',
      orderDetail: 'Chi tiết đơn hàng',
      orderItems: 'Sản phẩm',
      receiverInfo: 'Thông tin người nhận',
      paymentMethod: 'Phương thức thanh toán',
      paymentStatus: 'Tình trạng thanh toán',
      paid: 'Đã thanh toán',
      unpaid: 'Chưa thanh toán',
      shippingAddress: 'Địa chỉ giao hàng',
      orderTimeline: 'Lịch sử đơn hàng',
      cancelOrder: 'Huỷ đơn',
      confirmCancel: 'Bạn có chắc muốn huỷ đơn này?',
      cancelSuccess: 'Đã huỷ đơn hàng.',
      reorder: 'Mua lại',
      reorderSuccess: 'Đã thêm sản phẩm vào giỏ hàng.',
      summary: 'Tóm tắt',
      subtotal: 'Tạm tính',
      shippingFee: 'Phí vận chuyển',
      discount: 'Giảm giá',
      grandTotal: 'Tổng cộng',
    },
    voucher: {
      title: 'Kho Voucher',
      myVouchers: 'Voucher của tôi',
      publicVouchers: 'Voucher khả dụng',
      code: 'Mã',
      discount: 'Giảm',
      minSpend: 'Đơn tối thiểu',
      expiry: 'Hạn sử dụng',
      useNow: 'Dùng ngay',
      noVouchers: 'Bạn chưa có voucher nào khả dụng.',
      save: 'Lưu',
      saved: 'Đã lưu',
      copy: 'Sao chép mã',
      copied: 'Đã sao chép',
      expired: 'Hết hạn',
      status: 'Trạng thái',
    },
    theme: {
      light: 'Sáng',
      dark: 'Tối',
      switchToLight: 'Chuyển sang chế độ sáng',
      switchToDark: 'Chuyển sang chế độ tối',
    },
  },
  en: {
    nav: {
      home: 'Home',
      products: 'Products',
      brand: 'Brand',
      offers: 'Offers',
      contact: 'Contact',
      searchPlaceholder: 'Search products...',
      searchNoResults: 'No results found for "{query}"',
      searchViewAll: 'View all products',
      admin: 'Administrator',
      staff: 'Staff',
      customer: 'Customer',
      welcome: 'Welcome, {name}',
      logout: 'Log out',
      myAccount: 'My Account',
      adminPanel: 'Go to Admin Portal',
      backToWebsite: 'Back to Website',
      loginOrRegister: 'Sign In / Register',
      searchProduct: 'Search products',
      close: 'Close'
    },
    notifications: {
      title: 'Notifications',
      empty: 'No new notifications',
      markAllRead: 'Mark all as read',
      viewAll: 'View all',
      justNow: 'Just now'
    },
    home: {
      heroSub: 'Fall-Winter Collection 2026',
      heroTitle: 'Redefining sophistication.',
      heroDesc: 'Discover highly curated pieces blending traditional craftsmanship with contemporary design thinking.',
      heroBtn: 'Shop Now',
      categoriesTitle: 'Featured Categories',
      categoriesSub: 'Explore worlds of distinctive style',
      viewAllCategories: 'View All Categories',
      explore: 'Explore Now',
      newArrivalsTitle: 'New Arrivals',
      newArrivalsSub: 'Latest additions to Aura K, ready to elevate your style signature.',
      newsletterTitle: 'Join the Aura K Community',
      newsletterDesc: 'Subscribe for updates on exclusive limited collections and modern style trends.',
      newsletterPlaceholder: 'Your email address',
      newsletterBtn: 'Subscribe',
      newsletterSuccess: 'Wonderful! Redirecting you to register...',
      newsletterRegistered: 'This email is already registered. Please log in!',
      feature1Title: 'Curated Quality',
      feature1Desc: 'Each item undergoes rigorous quality controls regarding origin and materials before delivery.',
      feature2Title: 'Priority Shipping',
      feature2Desc: 'Experience premium, secure delivery nationwide within 24 to 48 hours.',
      feature3Title: 'Member Privilege',
      feature3Desc: 'Join Aura K Elite for exclusive discounts, priority restocks, and private event invites.',
      fallbackSubtitle: {
        pants: 'Dynamic and comfortable',
        jackets: 'Stylishly warm',
        tshirts: 'Comfortable everyday essential',
        dresses: 'Graceful and feminine',
        women: 'Timeless luxury and elegance',
        men: 'Sharp and dapper look',
        home: 'Elevate your living space',
        accessories: 'The perfect finishing touch'
      },
      premiumLabel: 'Premium',
      premiumBrandsTitle: 'Premium Brands',
      premiumBrandsSub: 'Boutique labels defined by curated materials and elevated design.',
      premiumBadge: 'Couture',
      noBrandTier: 'Unclassified (missing backend info)',
      noBrandData: 'No brand data available',
      mainstreamLabel: 'Mainstream',
      mainstreamBrandsTitle: 'Everyday Brands',
      mainstreamBrandsSub: 'Accessible labels for agile, modern living.',
      mainstreamBadge: 'Street',
      brandExplore: 'Discover'
    },
    footer: {
      desc: 'Founded with a vision to deliver sustainable aesthetic values, Aura K is the destination for souls seeking sophistication and uniqueness in every fine detail.',
      explore: 'Explore',
      support: 'Support',
      collections: 'Collections',
      newArrivals: 'New Arrivals',
      men: 'Men\'s',
      women: 'Women\'s',
      contact: 'Contact Us',
      stores: 'Store Locator',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      partners: 'Partners & Sponsors',
      rights: '© 2026 Aura K. All rights reserved.'
    },
    checkout: {
      title: 'Checkout',
      shippingAddress: 'Shipping Address',
      shippingInfo: 'Shipping Info',
      complete: 'Complete',
      contactInfo: 'Contact Information',
      alreadyHaveAccount: 'Already have an account?',
      street: 'Street Address',
      lastName: 'Last Name',
      firstName: 'First Name',
      fullName: 'Full Name',
      fullNamePlaceholder: 'Enter your full name...',
      phone: 'Phone Number',
      phonePlaceholder: 'Enter your phone number...',
      city: 'Province / City',
      cityPlaceholder: 'Select Province / City',
      district: 'District',
      districtPlaceholder: 'Select District',
      ward: 'Ward / Commune',
      wardPlaceholder: 'Select Ward / Commune',
      addressDetail: 'Street Address',
      addressDetailPlaceholder: 'Building, house number, street...',
      paymentMethod: 'Payment Method',
      cod: 'Cash on Delivery (COD)',
      codDesc: 'Pay with cash upon delivery.',
      onlinePayment: 'MoMo E-wallet Payment',
      onlinePaymentDesc: 'Use MoMo app to scan QR code for quick payment.',
      bankTransfer: 'Bank Transfer (Vietcombank)',
      bankTransferDesc: 'Direct transfer to the shop\'s bank account.',
      orderSummary: 'Order Details',
      placeOrder: 'Place Order Now',
      orderSuccessTitle: 'Order Placed Successfully!',
      orderSuccessMessage: 'Thank you for shopping at Aura K. Your order has been received and is being processed.',
      orderId: 'Order ID',
      backToHome: 'Back to Homepage',
      requiredFields: 'Please fill in all required shipping fields!',
      loading: 'Processing...',
      cartEmpty: 'Your cart is empty. Please add products before checking out.'
    },
    account: {
      sidebarAccount: 'My Profile',
      sidebarOrders: 'My Orders',
      sidebarAddresses: 'Address Book',
      sidebarVouchers: 'Vouchers & Coupons',
      sidebarLogout: 'Sign Out',
      profile: 'My Profile',
      profileSub: 'Manage profile information for account security',
      personalInfo: 'Personal Information',
      edit: 'Edit Details',
      save: 'Save Changes',
      firstName: 'First Name',
      lastName: 'Last Name',
      username: 'Username',
      phone: 'Phone Number',
      email: 'Email Address',
      gender: 'Gender',
      male: 'Male',
      female: 'Female',
      other: 'Other',
      addressBook: 'Address Book',
      addNewAddress: 'Add New Address',
      noAddresses: 'You have no saved addresses yet.',
      orderHistory: 'Order History',
      orderId: 'Order ID',
      date: 'Order Date',
      total: 'Total Amount',
      status: 'Status',
      viewDetail: 'View Details',
      noOrders: 'You have not placed any orders yet.',
      voucherCode: 'Code',
      discount: 'Off',
      minSpend: 'Min spend',
      expiry: 'Expires',
      useNow: 'Use Now',
      noVouchers: 'No vouchers available.',
      orderDetail: 'Order Details',
      backToHistory: 'Back to Order History',
      receiverInfo: 'Recipient Information',
      paymentStatus: 'Payment Status',
      paid: 'Paid',
      unpaid: 'Unpaid',
      orderStatus: {
        pending: 'Pending Confirm',
        confirmed: 'Confirmed',
        shipping: 'Shipping',
        delivered: 'Delivered',
        cancelled: 'Cancelled'
      }
    },
    loginRegister: {
      loginTitle: 'Welcome Back',
      loginDesc: 'Log in to your account to resume your shopping journey at Aura K.',
      registerTitle: 'Create An Account',
      registerDesc: 'Register to unlock premium member benefits and manage your orders.',
      email: 'Email Address',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      forgotPassword: 'Forgot Password?',
      loginBtn: 'Log In',
      registerBtn: 'Register',
      noAccount: 'Don\'t have an account?',
      hasAccount: 'Already have an account?',
      googleLogin: 'Sign In with Google',
      facebookLogin: 'Sign In with Facebook',
      username: 'Account Username',
      required: 'This field is required'
    },
    common: {
      yes: 'Yes',
      no: 'No',
      cancel: 'Cancel',
      confirm: 'Confirm',
      save: 'Save',
      edit: 'Edit',
      delete: 'Delete',
      loading: 'Loading...',
      seeMore: 'See more',
      seeLess: 'See less',
      search: 'Search',
      all: 'All',
      back: 'Back',
      next: 'Next',
      previous: 'Previous',
      or: 'or',
      and: 'and',
      from: 'From',
      to: 'to',
      free: 'Free',
      sold: 'sold',
      welcome: 'Welcome',
      error: 'Error',
      success: 'Success',
      processing: 'Processing...',
      empty: 'No data',
      retry: 'Try again',
    },
    header: {
      searchPlaceholder: 'Search products, brands...',
      darkMode: 'Dark mode',
      lightMode: 'Light mode',
      languageLabel: 'Language',
      notifications: 'Notifications',
      markAllRead: 'Mark all as read',
      noNotifications: 'No new notifications',
      viewAllNotifs: 'View all',
      cart: 'Cart',
      emptyCart: 'Cart is empty',
      wishlist: 'Wishlist',
      accountMenu: 'Account',
      login: 'Log In',
      register: 'Sign Up',
      customerService: 'Customer support',
      hotlineLabel: 'Hotline',
    },
    products: {
      title: 'All Products',
      filterCategory: 'Category',
      filterBrand: 'Brand',
      filterPrice: 'Price Range',
      sortBy: 'Sort By',
      sortNewest: 'Newest',
      sortPriceAsc: 'Price: Low to High',
      sortPriceDesc: 'Price: High to Low',
      sortBestSell: 'Best Selling',
      sortAZ: 'Name: A-Z',
      sortZA: 'Name: Z-A',
      searchLabel: 'Search',
      noProducts: 'No products matched your search criteria.',
      tryDifferent: 'Try adjusting your filters or search keywords.',
      allCategories: 'All Categories',
      allBrands: 'All Brands',
      priceFrom: 'Min',
      priceTo: 'Max',
      applyFilter: 'Apply Filter',
      clearFilter: 'Reset Filters',
      showingResults: 'Showing {count} products',
      category: 'Category',
      brand: 'Brand',
      addToCart: 'Add to Cart',
      newBadge: 'New',
      outOfStock: 'Out of stock',
      inStock: 'In stock',
      filterTitle: 'Filters',
      view: 'View',
      viewAll: 'View all',
      results: 'results',
      auraKBrand: 'Aura K',
    },
    productDetail: {
      addToCart: 'Add to Cart',
      buyNow: 'Buy Now',
      outOfStock: 'Out of Stock',
      description: 'Description',
      specs: 'Specifications',
      reviews: 'Reviews',
      relatedProducts: 'Related Products',
      relatedDesc: 'You might also love these curated recommendations.',
      size: 'Size',
      color: 'Color',
      quantity: 'Quantity',
      share: 'Share',
      addSuccess: 'Product successfully added to cart!',
      brand: 'Brand',
      category: 'Category',
      status: 'Availability',
      inStock: 'In Stock',
      sold: 'Sold',
      rating: 'Rating',
      writeReview: 'Write a Review',
      reviewPlaceholder: 'Share your experience...',
      submitReview: 'Submit Review',
      reviewSubmitted: 'Thanks for your review!',
      noReviews: 'No reviews yet for this product.',
      viewCart: 'View Cart',
      backToShop: 'Continue Shopping',
      sku: 'SKU',
      tags: 'Tags',
      flashSale: 'Flash Sale',
      customerReviews: 'Customer Reviews',
      reviewsTitle: 'Voices From Our Community',
      yourRating: 'Your Rating',
      yourComment: 'Your Comment',
      loginToReview: 'Please log in to submit a review.',
      loginToReviewMessage: 'Please log in to share your experience with this product.',
      emptyReview: 'Please enter your review comment.',
      reviewFailed: 'Unable to submit review right now.',
      serverError: 'Server connection error.',
      loading: 'Loading product details...',
      loadingReviews: 'Loading reviews...',
      notFound: 'Product not found.',
      connectionError: 'Unable to connect to the server.',
      selectSize: 'Please select a size!',
      selectColor: 'Please select a color!',
      sizeGuide: 'Size Guide',
      sizeGuideUnit: 'Unit: cm',
      howToMeasure: 'How to Measure',
      chest: 'Chest',
      chestDesc: 'Measure around the fullest part of your chest, keeping the tape horizontal.',
      waist: 'Waist',
      waistDesc: 'Measure around the narrowest part of your waist, usually 2–3cm above your belly button.',
      hips: 'Hips',
      hipsDesc: 'Measure around the widest part of your hips.',
      height: 'Height',
      sizeTip: 'For the best comfort, if your measurements fall between two sizes, we recommend choosing the larger size.',
      gotIt: 'Got it',
      auraCustomer: 'Aura K Customer',
      noComment: 'No comment left.',
      beFirstReviewer: 'Be the first to share your experience with this product.',
      youMayAlsoLike: 'You May Also Like',
    },
    cart: {
      title: 'Your Cart',
      empty: 'Empty Cart',
      emptySub: 'There are currently no products in your shopping cart.',
      backToShop: 'Return to Shop',
      product: 'Product',
      price: 'Price',
      quantity: 'Quantity',
      total: 'Total',
      summary: 'Order Summary',
      subtotal: 'Subtotal',
      shipping: 'Shipping',
      shippingFree: 'Free',
      checkout: 'Proceed to Checkout',
      remove: 'Remove',
      clear: 'Clear All',
      discount: 'Discount',
      voucher: 'Promo Code',
      applyVoucher: 'Apply',
      voucherPlaceholder: 'Enter discount code...',
      voucherApplied: 'Discount code {code} applied successfully!',
      voucherInvalid: 'Invalid or expired discount code.',
      voucherExpired: 'This code has expired.',
      continueShopping: 'Continue Shopping',
      cartUpdated: 'Cart updated.',
      removedItem: 'Item removed from cart.',
      orderSummary: 'Order Summary',
    },
    contact: {
      title: 'Contact Us',
      subtitle: 'We are always happy to hear from you',
      name: 'Full Name',
      namePlaceholder: 'Enter your full name...',
      email: 'Email Address',
      emailPlaceholder: 'you@example.com',
      phone: 'Phone Number',
      phonePlaceholder: 'Enter your phone number...',
      subject: 'Subject',
      subjectPlaceholder: 'What would you like to discuss?',
      message: 'Message',
      messagePlaceholder: 'Type your message...',
      send: 'Send Message',
      sending: 'Sending...',
      sendSuccess: 'Message sent successfully! We will get back to you soon.',
      sendError: 'Failed to send. Please try again later.',
      ourInfo: 'Get in Touch',
      ourAddress: 'Address',
      ourPhone: 'Phone',
      ourEmail: 'Email',
      ourHours: 'Opening Hours',
      faqTitle: 'Frequently Asked Questions',
      followUs: 'Follow Us',
    },
    address: {
      title: 'Address Book',
      addNew: 'Add New Address',
      noAddresses: 'You have no saved addresses yet. Add one to check out faster.',
      recipientName: 'Recipient name',
      recipientPhone: 'Phone number',
      addressDetail: 'Street address',
      city: 'Province / City',
      district: 'District',
      ward: 'Ward / Commune',
      isDefault: 'Set as default address',
      setDefault: 'Set Default',
      edit: 'Edit',
      delete: 'Delete',
      confirmDelete: 'Are you sure you want to delete this address?',
      addSuccess: 'Address added successfully.',
      updateSuccess: 'Address updated.',
      deleteSuccess: 'Address deleted.',
      selectAddress: 'Select address',
      defaultLabel: 'Default',
      empty: 'No addresses yet',
      loading: 'Loading addresses...',
      required: 'Please fill in all required fields.',
    },
    order: {
      title: 'My Orders',
      orderId: 'Order ID',
      orderDate: 'Order Date',
      totalAmount: 'Total Amount',
      status: 'Status',
      viewDetail: 'View Details',
      noOrders: 'You have not placed any orders yet.',
      backToShop: 'Start Shopping',
      orderDetail: 'Order Details',
      orderItems: 'Items',
      receiverInfo: 'Recipient Information',
      paymentMethod: 'Payment Method',
      paymentStatus: 'Payment Status',
      paid: 'Paid',
      unpaid: 'Unpaid',
      shippingAddress: 'Shipping Address',
      orderTimeline: 'Order Timeline',
      cancelOrder: 'Cancel Order',
      confirmCancel: 'Are you sure you want to cancel this order?',
      cancelSuccess: 'Order cancelled.',
      reorder: 'Reorder',
      reorderSuccess: 'Items added to cart.',
      summary: 'Summary',
      subtotal: 'Subtotal',
      shippingFee: 'Shipping Fee',
      discount: 'Discount',
      grandTotal: 'Grand Total',
    },
    voucher: {
      title: 'Vouchers & Coupons',
      myVouchers: 'My Vouchers',
      publicVouchers: 'Available Vouchers',
      code: 'Code',
      discount: 'Off',
      minSpend: 'Min spend',
      expiry: 'Expires',
      useNow: 'Use Now',
      noVouchers: 'No vouchers available right now.',
      save: 'Save',
      saved: 'Saved',
      copy: 'Copy code',
      copied: 'Copied',
      expired: 'Expired',
      status: 'Status',
    },
    filter: {
      title: 'Filters',
      category: 'Category',
      brand: 'Brand',
      price: 'Price',
      rating: 'Rating',
      reset: 'Reset',
      apply: 'Apply',
      showing: 'Showing',
      of: 'of',
      products: 'products',
    },
    theme: {
      light: 'Light',
      dark: 'Dark',
      switchToLight: 'Switch to light mode',
      switchToDark: 'Switch to dark mode',
    },
  },
};

export const LanguageProvider = ({ children }) => {
  // Đọc ngôn ngữ từ localStorage nếu có, mặc định là 'vi' (tiếng Việt)
  const [language, setLanguage] = useState(() => {
    const savedLang = localStorage.getItem('auraKLanguage');
    return savedLang === 'en' || savedLang === 'vi' ? savedLang : 'vi';
  });

  const changeLanguage = (lang) => {
    if (lang === 'en' || lang === 'vi') {
      setLanguage(lang);
      localStorage.setItem('auraKLanguage', lang);
    }
  };

  const formatPrice = (price) => {
    if (price === undefined || price === null) return '';
    const num = Number(price);
    if (language === 'vi') {
      return num.toLocaleString('vi-VN') + 'đ';
    } else {
      const usdPrice = num / 25000;
      return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(usdPrice);
    }
  };

  // Hàm dịch theo key có cấu trúc dạng 'section.key' (vd: 'nav.products')
  const t = useMemo(() => (keyPath, params = {}) => {
    const parts = keyPath.split('.');
    const tryLookup = (lang) => {
      let result = translations[lang];
      for (const part of parts) {
        if (result && typeof result === 'object' && part in result) {
          result = result[part];
        } else {
          return null;
        }
      }
      return typeof result === 'string' ? result : null;
    };

    let translated = tryLookup(language);
    if (translated == null) {
      const fallbackLang = language === 'en' ? 'vi' : 'en';
      translated = tryLookup(fallbackLang);
    }
    if (translated == null) {
      translated = keyPath;
    }

    let formattedString = translated;
    Object.keys(params).forEach((paramKey) => {
      formattedString = formattedString.replace(new RegExp(`{${paramKey}}`, 'g'), params[paramKey]);
    });

    return formattedString;
  }, [language]);

  const contextValue = React.useMemo(() => ({
    language,
    changeLanguage,
    t,
    formatPrice,
    translateCategoryName: (name) => translateCategoryName(name, language),
    translateOrderStatus: (status) => translateOrderStatus(status, language),
    translateProductName: (name) => translateProductName(name, language),
    translateProductDescription: (desc) => translateProductDescription(desc, language),
    translateColorName: (color) => translateColorName(color, language),
  }), [language, t, formatPrice]);

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
